name: bin_field
description: A Dart library for binary field operations and protocol handling.
version: 0.0.3

environment:
  sdk: ^3.5.4

repository: https://github.com/QingmingPlusPlus/bin_field

dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
